book_data = {
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "First Corinthians": 16,
    "Second Corinthians": 12,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "First Thessalonians": 5,
    "Second Thessalonians": 3,
    "First Timothy": 6,
    "Second Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "First Peter": 5,
    "Second Peter": 3,
    "First John": 5,
    "Second John": 1,
    "Third John": 1,
    "Jude": 1,
    "Revelation": 22,
}