"""empty message

Revision ID: 25e0d7a24066
Revises: 02a6c2921660
Create Date: 2021-02-26 12:20:44.716380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e0d7a24066'
down_revision = '02a6c2921660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_testament', sa.Column('amplified', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_testament', 'amplified')
    # ### end Alembic commands ###
